### ISSUE TITLE
Unable to delete the archive after extracting using extractor.ExtractToDirectory

### ISSUE THREAD

**Issue by c0bra99** [microsoft/RecursiveExtractor#149]
I am trying to replace the usage of System.IO.Compression.ZipFile.ExtractToDirectory() with the Microsoft.CST.RecursiveExtractor nuget package

I am using this code to extract a zip file, then trying to delete it, but the zip file is still in use.
`  var extractor = new Extractor();
  var extractorOptions = new ExtractorOptions();
  extractor.ExtractToDirectory(outputDirectory, sourceArchiveFileName, extractorOptions);`

It seems that Extractor does not implement IDisposable and there is no way to close the archive. Am I missing anything necessary to close the archive after extracting it?

Attached is an example console app reproducing the issue
[NetFrameworkConsoleApp.zip](https://github.com/microsoft/RecursiveExtractor/files/14607962/NetFrameworkConsoleApp.zip)

**Comment by gfs** [comment]
Try using the `public ExtractionStatusCode ExtractToDirectory(string outputDirectory, string filename, Stream stream, ExtractorOptions? opts = null, bool printNames = false)` API instead so you can control the lifecycle of the `Stream`. If you use the `public ExtractionStatusCode ExtractToDirectory(string outputDirectory, string filename, ExtractorOptions? opts = null, bool printNames = false)` method under the covers it will call `FileEntry.FromFileName(filename)` which creates a Stream owned by the FileEntry object. The Stream is then disposed by the FileEntry [finalizer](https://github.com/microsoft/RecursiveExtractor/blob/92962d66075db2018cd8b24e1069403abc4f47fb/RecursiveExtractor/FileEntry.cs#L207-L213) but it is non-deterministic when the finalizer runs.

I modified your example slightly to use the alternate API and it seems to resolve the issue:
```csharp
        private static void ExtractToDirectory(string sourceArchiveFileName, string outputDirectory)
        {
            var extractor = new Extractor();
            var extractorOptions = new ExtractorOptions();
            var fileStream = File.OpenRead(sourceArchiveFileName);
            extractor.ExtractToDirectory(outputDirectory, sourceArchiveFileName, fileStream, extractorOptions);
            fileStream.Dispose();
        }
```
![image](https://github.com/microsoft/RecursiveExtractor/assets/98900/ddfa43fe-fb8a-4630-ab8c-d45a51ed1e84)

It would probably be better to switch the filename API to instead open the stream and then dispose it after extraction rather than relying on the FileEntry finalizer.

**Comment by c0bra99** [comment]
Thank you, using the FileStream overload is a good workaround for now, and I see you opened a PR that should fix the original method in the future. Thanks for the quick help!
